[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/"

# DO NOT delete anything below this line!

[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/success"

[[edge_functions]]
  function = "buttondown-lookup"
  path = "/lookup"
