[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/"

[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/success"

[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/login"

[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/nosub"

[[edge_functions]]
  function = "buttondown-cookie-check"
  path = "/error"

[[edge_functions]]
  function = "buttondown-redirect"
  path = "/redirection-example"

[[edge_functions]]
  function = "buttondown-lookup"
  path = "/lookup"
